# Site settings
site.locale: "en-US"
title: "Nick's Corner"  # The title of your website
description: "Biomedical Engineering Student | Medical Devices & Bionic Prosthesis Enthusiast"  # A short description of yourself
url: "https://fettuccinifelix.github.io"  # The URL of your site
logo: /assets/img/Nick Santoso (1).jpg

# Theme settings (if using a Jekyll theme)
theme: jekyll-theme-minimal  # The theme you're using (adjust if you're using a specific one)
